# Generated by Django 5.2.2 on 2025-06-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='address',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
