# Generated by Django 5.2.2 on 2025-06-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_borrower_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default=True, max_length=20),
            preserve_default=False,
        ),
    ]
