# Generated by Django 5.2.2 on 2025-06-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_loan_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_code',
            field=models.CharField(default=True, editable=False, max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
