# Generated by Django 5.2.2 on 2025-06-11 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_loan_borrower_alter_payment_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.borrower'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='borrower',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.borrower'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.loan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='borrower',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.borrower'),
            preserve_default=False,
        ),
    ]
