# Generated by Django 5.2.2 on 2025-06-12 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_loan_borrower_alter_payment_borrower_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='email',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='name',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='phone',
        ),
        migrations.AlterField(
            model_name='borrower',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
