# Generated by Django 5.2.2 on 2025-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_borrower_email_remove_borrower_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
